### ISSUE TITLE
Required Permission Callback

### ISSUE THREAD

**Issue by jmbarne3** [UCF/UCF-Degree-CPT-Plugin#123]
**Describe the bug**
WP Core now required the `permission_callback` parameter be defined for all rest routes. We will need to make sure the rest routes in this project have that parameter set when they're created. We can just set them to `__return_true` since they're all public routes.

**Steps to Reproduce**

1. Call the rest route on WP 5.9+
2. Observe the notice being thrown in the logs

**Expected Behavior**
We shouldn't see a notice being thrown when the API is called.

**Comment by rjucf** [comment]
Fixed with #124
