### ISSUE TITLE
Need to add validation in return_verified_result() to ensure $results is an array

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Degree-CPT-Plugin#83]
We've started seeing the following error pop up repeatedly during degree post imports:

PHP Warning:  Invalid argument supplied for foreach() in UCF-Degree-CPT-Plugin/common/ucf-degree-common.php on line 156

https://github.com/UCF/UCF-Degree-CPT-Plugin/blob/master/common/ucf-degree-common.php#L156

**Comment by jmbarne3** [comment]
Resolved in v3.2.1 #84
